(async () => {
  let store = window.PURE20_API.normalizeStore(window.PURE20_FALLBACK_STORE);
  let source = window.PURE20_API.configured ? 'cloud' : 'demo';
  const $ = id => document.getElementById(id);
  const els = {
    loginGate:$('loginGate'),emailInput:$('emailInput'),passwordInput:$('passwordInput'),loginButton:$('loginButton'),demoButton:$('demoButton'),loginError:$('loginError'),authIntro:$('authIntro'),loginHelp:$('loginHelp'),cloudLoginFields:$('cloudLoginFields'),adminStatus:$('adminStatus'),adminUser:$('adminUser'),signOut:$('signOut'),syncNote:$('syncNote'),demoAlert:$('demoAlert'),cloudAlert:$('cloudAlert'),productsBody:$('productsBody'),couponsBody:$('couponsBody'),productSearch:$('productSearch'),productCategory:$('productCategory'),productStatus:$('productStatus'),productModal:$('productModal'),couponModal:$('couponModal'),modalBackdrop:$('modalBackdrop'),fileInput:$('fileInput')
  };
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid=prefix=>`${prefix}-${(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2))}`;
  const money=v=>`${store.settings.currencySymbol||'€'}${Number(v||0).toFixed(2)}`;

  function setSync(kind,text){els.syncNote.className=`sync-note ${kind==='pending'?'pending':kind==='error'?'error':''}`;els.syncNote.innerHTML=`<span class="cloud-dot"></span><span>${esc(text)}</span>`;}
  function setModeUI(){
    const live=source==='cloud';
    els.adminStatus.className=`admin-status ${live?'live':'demo'}`;
    els.adminStatus.innerHTML=`<span class="cloud-dot"></span><span>${live?'Cloud / live':'Demo / local'}</span>`;
    els.demoAlert.hidden=live;els.cloudAlert.hidden=!live;
    setSync('',live?'Connected to shared database':'Demo data saved on this browser');
  }

  function renderStats(){$('statActive').textContent=store.products.filter(p=>p.active).length;$('statStock').textContent=store.products.reduce((s,p)=>s+Number(p.stock||0),0);$('statCategories').textContent=new Set(store.products.map(p=>p.category).filter(Boolean)).size;$('statCoupons').textContent=store.coupons.filter(c=>c.active).length;}
  function renderCategories(){const cats=['All',...new Set(store.products.map(p=>p.category).filter(Boolean).sort())];const cur=els.productCategory.value||'All';els.productCategory.innerHTML=cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');els.productCategory.value=cats.includes(cur)?cur:'All';}
  function filteredProducts(){const q=els.productSearch.value.trim().toLowerCase(),cat=els.productCategory.value||'All',status=els.productStatus.value||'all';return [...store.products].sort((a,b)=>a.order-b.order||a.product.localeCompare(b.product)).filter(p=>{const text=`${p.product} ${p.variant} ${p.code} ${p.category}`.toLowerCase();return(!q||text.includes(q))&&(cat==='All'||p.category===cat)&&(status==='all'||(status==='active'&&p.active)||(status==='inactive'&&!p.active)||(status==='out'&&p.stock<=0));});}
  function renderProducts(){const rows=filteredProducts();els.productsBody.innerHTML=rows.length?rows.map(p=>`<tr data-id="${esc(p.id)}"><td>${p.order}</td><td><strong>${esc(p.product)}</strong>${p.badge?`<div class="data-source-note">${esc(p.badge)}</div>`:''}</td><td>${esc(p.variant)}</td><td>${esc(p.category)}</td><td>${esc(p.code)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><span class="status-chip ${p.active?'chip-on':'chip-off'}">${p.active?(p.stock>0?'Active':'Out of stock'):'Hidden'}</span></td><td><div class="row-actions"><button class="row-btn" data-act="edit">Edit</button><button class="row-btn" data-act="toggle">${p.active?'Hide':'Show'}</button><button class="row-btn" data-act="delete">Delete</button></div></td></tr>`).join(''):`<tr><td colspan="9"><div class="admin-empty">No products match these filters.</div></td></tr>`;}
  function renderCoupons(){els.couponsBody.innerHTML=store.coupons.length?store.coupons.map(c=>`<tr data-id="${esc(c.id)}"><td><strong>${esc(c.code)}</strong></td><td>${c.type==='fixed'?'Fixed':'Percent'}</td><td>${c.type==='fixed'?money(c.value):`${c.value}%`}</td><td>${money(c.minSubtotal)}</td><td><span class="status-chip ${c.active?'chip-on':'chip-off'}">${c.active?'Active':'Inactive'}</span></td><td><div class="row-actions"><button class="row-btn" data-cact="edit">Edit</button><button class="row-btn" data-cact="toggle">${c.active?'Disable':'Enable'}</button><button class="row-btn" data-cact="delete">Delete</button></div></td></tr>`).join(''):`<tr><td colspan="6"><div class="admin-empty">No coupon codes.</div></td></tr>`;}
  function renderSettings(){const s=store.settings;$('setBrand').value=s.brandName||'';$('setSymbol').value=s.currencySymbol||'€';$('setCurrency').value=s.currency||'EUR';$('setShipping').value=s.shippingFlat||0;$('setFreeShipping').value=s.freeShippingThreshold||0;$('setLowStock').value=s.lowStockThreshold||5;$('setShippingText').value=s.shippingText||'';$('setWhatsapp').value=s.whatsappNumber||'';$('setEyebrow').value=s.eyebrow||'';$('setTitle').value=s.title||'';$('setSubtitle').value=s.subtitle||'';$('setFooter').value=s.footerNotice||'';}
  function renderAll(){renderStats();renderCategories();renderProducts();renderCoupons();renderSettings();setModeUI();}

  async function reloadStore(){const r=await window.PURE20_API.adminLoadAll();store=r.store;source=r.source;renderAll();}
  async function mutate(label,fn){setSync('pending',label);document.body.classList.add('saving');try{await fn();await reloadStore();setSync('',source==='cloud'?'Saved to cloud':'Saved in demo mode');}catch(err){console.error(err);setSync('error',err.message||'Save failed');alert(`Could not save: ${err.message||err}`);}finally{document.body.classList.remove('saving');}}

  document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${b.dataset.tab}`));}));
  [els.productSearch,els.productCategory,els.productStatus].forEach(x=>x.addEventListener('input',renderProducts));
  function openModal(el){els.modalBackdrop.classList.add('open');el.classList.add('open')}
  function closeModals(){els.modalBackdrop.classList.remove('open');els.productModal.classList.remove('open');els.couponModal.classList.remove('open')}
  document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModals));els.modalBackdrop.addEventListener('click',closeModals);

  function productToForm(p){$('prodId').value=p?.id||'';$('prodName').value=p?.product||'';$('prodVariant').value=p?.variant||'';$('prodCode').value=p?.code||'';$('prodCategory').value=p?.category||'';$('prodUnit').value=p?.unit||'vial';$('prodPrice').value=p?.price??'';$('prodStock').value=p?.stock??20;$('prodOrder').value=p?.order??Math.max(0,...store.products.map(x=>Number(x.order)||0))+1;$('prodBadge').value=p?.badge||'';$('prodNote').value=p?.note||'';$('prodCoaUrl').value=p?.coaUrl||'';$('prodActive').value=String(p?.active!==false);$('productModalTitle').textContent=p?'Edit product':'Add product'}
  $('addProduct').addEventListener('click',()=>{productToForm(null);openModal(els.productModal)});
  els.productsBody.addEventListener('click',e=>{const tr=e.target.closest('tr[data-id]'),b=e.target.closest('[data-act]');if(!tr||!b)return;const p=store.products.find(x=>x.id===tr.dataset.id);if(!p)return;if(b.dataset.act==='edit'){productToForm(p);openModal(els.productModal)}else if(b.dataset.act==='toggle'){mutate(p.active?'Hiding product…':'Showing product…',()=>window.PURE20_API.adminUpsertProduct({...p,active:!p.active}))}else if(b.dataset.act==='delete'&&confirm(`Delete ${p.product} ${p.variant}?`)){mutate('Deleting product…',()=>window.PURE20_API.adminDeleteProduct(p.id))}});
  $('saveProduct').addEventListener('click',()=>{const id=$('prodId').value;const p={id:id||uid('product'),product:$('prodName').value.trim(),variant:$('prodVariant').value.trim(),code:$('prodCode').value.trim(),category:$('prodCategory').value.trim()||'Other',unit:$('prodUnit').value.trim()||'vial',price:Math.max(0,Number($('prodPrice').value)||0),stock:Math.max(0,Math.floor(Number($('prodStock').value)||0)),order:Number($('prodOrder').value)||1,badge:$('prodBadge').value.trim(),note:$('prodNote').value.trim(),coaUrl:$('prodCoaUrl').value.trim(),active:$('prodActive').value==='true'};if(!p.product){alert('Product name is required.');return}closeModals();mutate('Saving product…',()=>window.PURE20_API.adminUpsertProduct(p));});

  function couponToForm(c){$('couponId').value=c?.id||'';$('couponCode').value=c?.code||'';$('couponType').value=c?.type||'percent';$('couponValue').value=c?.value??10;$('couponMin').value=c?.minSubtotal??0;$('couponActive').value=String(c?.active!==false);$('couponModalTitle').textContent=c?'Edit coupon':'Add coupon'}
  $('addCoupon').addEventListener('click',()=>{couponToForm(null);openModal(els.couponModal)});
  els.couponsBody.addEventListener('click',e=>{const tr=e.target.closest('tr[data-id]'),b=e.target.closest('[data-cact]');if(!tr||!b)return;const c=store.coupons.find(x=>x.id===tr.dataset.id);if(!c)return;if(b.dataset.cact==='edit'){couponToForm(c);openModal(els.couponModal)}else if(b.dataset.cact==='toggle'){mutate(c.active?'Disabling coupon…':'Enabling coupon…',()=>window.PURE20_API.adminUpsertCoupon({...c,active:!c.active}))}else if(b.dataset.cact==='delete'&&confirm(`Delete coupon ${c.code}?`)){mutate('Deleting coupon…',()=>window.PURE20_API.adminDeleteCoupon(c.id))}});
  $('saveCoupon').addEventListener('click',()=>{const id=$('couponId').value,c={id:id||uid('coupon'),code:$('couponCode').value.trim().toUpperCase(),type:$('couponType').value,value:Math.max(0,Number($('couponValue').value)||0),minSubtotal:Math.max(0,Number($('couponMin').value)||0),active:$('couponActive').value==='true'};if(!c.code){alert('Coupon code is required.');return}closeModals();mutate('Saving coupon…',()=>window.PURE20_API.adminUpsertCoupon(c));});

  $('saveSettings').addEventListener('click',()=>{const settings={...store.settings,brandName:$('setBrand').value.trim()||'PURE20.',currencySymbol:$('setSymbol').value.trim()||'€',currency:$('setCurrency').value.trim()||'EUR',shippingFlat:Math.max(0,Number($('setShipping').value)||0),freeShippingThreshold:Math.max(0,Number($('setFreeShipping').value)||0),lowStockThreshold:Math.max(0,Number($('setLowStock').value)||0),shippingText:$('setShippingText').value.trim(),whatsappNumber:$('setWhatsapp').value.trim(),eyebrow:$('setEyebrow').value.trim(),title:$('setTitle').value.trim(),subtitle:$('setSubtitle').value.trim(),footerNotice:$('setFooter').value.trim()};mutate('Saving settings…',()=>window.PURE20_API.adminSaveSettings(settings));});

  function download(name,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
  function csvEscape(v){v=String(v??'');return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
  function exportCsv(){const h=['order','category','product','variant','code','unit','price_eur','stock','active','badge','note','coa_url'];const lines=[h.join(','),...[...store.products].sort((a,b)=>a.order-b.order).map(p=>[p.order,p.category,p.product,p.variant,p.code,p.unit,p.price,p.stock,p.active,p.badge,p.note,p.coaUrl||''].map(csvEscape).join(','))];download('pure20-catalog-v4.csv',lines.join('\n'),'text/csv')}
  $('exportCsv').addEventListener('click',exportCsv);
  $('exportJson').addEventListener('click',()=>download('pure20-v4-backup.json',JSON.stringify(store,null,2),'application/json'));
  $('downloadTemplate').addEventListener('click',()=>download('pure20-catalog-template.csv','order,category,product,variant,code,unit,price_eur,stock,active,badge,note,coa_url\n1,Metabolic,Example,10 mg,EX10,vial,40,20,true,Popular,,https://example.com/coa.pdf','text/csv'));
  function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i],n=text[i+1];if(ch==='"'&&q&&n==='"'){cell+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift().map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
  function csvProducts(text){return parseCsv(text).map((r,i)=>({id:r.id||uid('product'),order:Number(r.order)||i+1,category:r.category||'Other',product:r.product||r.name||'Untitled',variant:r.variant||'',code:r.code||'',unit:r.unit||'vial',price:Math.max(0,Number(r.price_eur??r.price)||0),stock:Math.max(0,Math.floor(Number(r.stock??20)||0)),active:String(r.active??'true').toLowerCase()!=='false',badge:r.badge||'',note:r.note||'',coaUrl:r.coa_url||r.coaUrl||''}))}
  async function importFile(file){try{const text=await file.text();if(file.name.toLowerCase().endsWith('.csv')){const products=csvProducts(text);if(!confirm(`Replace the current product catalogue with ${products.length} CSV rows?`))return;await mutate('Importing catalogue…',()=>window.PURE20_API.adminReplaceProducts(products));}else{const data=window.PURE20_API.normalizeStore(JSON.parse(text));if(!confirm('Import this backup? Products, coupons and settings will be upserted.'))return;setSync('pending','Importing backup…');for(const p of data.products)await window.PURE20_API.adminUpsertProduct(p);for(const c of data.coupons)await window.PURE20_API.adminUpsertCoupon(c);await window.PURE20_API.adminSaveSettings(data.settings);await reloadStore();setSync('','Backup imported');}}catch(err){console.error(err);setSync('error','Import failed');alert(`Import failed: ${err.message||err}`)}}
  els.fileInput.addEventListener('change',()=>{const f=els.fileInput.files[0];if(f)importFile(f);els.fileInput.value=''});
  function chooseFile(csvOnly=false){els.fileInput.accept=csvOnly?'.csv,text/csv':'.json,.csv,text/csv,application/json';els.fileInput.click()}
  $('importCsvBtn').addEventListener('click',()=>chooseFile(true));$('backupImport').addEventListener('click',()=>chooseFile(false));

  async function enterAdmin(userLabel){els.loginGate.classList.add('hidden');els.adminUser.textContent=userLabel||'';await reloadStore();}
  async function login(){els.loginError.textContent='';els.loginButton.disabled=true;els.loginButton.textContent='Signing in…';try{const data=await window.PURE20_API.signIn(els.emailInput.value.trim(),els.passwordInput.value);const ok=await window.PURE20_API.isAdmin();if(!ok){await window.PURE20_API.signOut();throw new Error('This account is signed in but is not listed as a PURE20 admin.')}const email=data?.user?.email||data?.session?.user?.email||els.emailInput.value.trim();await enterAdmin(email);}catch(err){els.loginError.textContent=err.message||'Sign-in failed.';}finally{els.loginButton.disabled=false;els.loginButton.textContent='Sign in';}}
  els.loginButton.addEventListener('click',login);els.passwordInput.addEventListener('keydown',e=>{if(e.key==='Enter')login()});
  els.demoButton.addEventListener('click',()=>enterAdmin('demo@pure20.local'));
  els.signOut.addEventListener('click',async()=>{try{await window.PURE20_API.signOut()}catch(_){}location.reload()});

  async function bootstrap(){
    if(!window.PURE20_API.configured){source='demo';els.cloudLoginFields.hidden=true;els.demoButton.hidden=false;els.authIntro.textContent='Supabase is not configured yet. You can preview the complete admin workflow in local demo mode.';els.loginHelp.textContent='To go live, run SETUP_SUPABASE.sql and fill in supabase-config.js.';return;}
    source='cloud';els.demoButton.hidden=true;els.cloudLoginFields.hidden=false;
    try{const session=await window.PURE20_API.getSession();if(session?.user){const ok=await window.PURE20_API.isAdmin();if(ok){await enterAdmin(session.user.email||'Admin');return}await window.PURE20_API.signOut();els.loginError.textContent='The existing session is not an authorised PURE20 admin.';}}
    catch(err){els.loginError.textContent=`Connection error: ${err.message||err}`;}
  }

  await bootstrap();
})();
