(async()=>{
const C=window.PURE20_SUPABASE_CONFIG||{},client=window.supabase.createClient(C.url,C.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),E={loginGate:$('loginGate'),loginEmail:$('loginEmail'),loginPassword:$('loginPassword'),signInBtn:$('signInBtn'),signUpBtn:$('signUpBtn'),loginError:$('loginError'),signOutBtn:$('signOutBtn'),accountEmail:$('accountEmail'),eyebrow:$('eyebrow'),pageTitle:$('pageTitle'),pageSubtitle:$('pageSubtitle'),search:$('search'),clearSearch:$('clearSearch'),categoryPills:$('categoryPills'),catalogue:$('catalogue'),emptyState:$('emptyState'),productCount:$('productCount'),variantCount:$('variantCount'),shippingText:$('shippingText'),footerNotice:$('footerNotice'),cartPacks:$('cartPacks'),cartVials:$('cartVials'),cartSubtotal:$('cartSubtotal'),headerCartCount:$('headerCartCount'),clearCart:$('clearCart'),reviewOrder:$('reviewOrder'),headerCart:$('headerCart'),drawer:$('orderDrawer'),backdrop:$('drawerBackdrop'),closeDrawer:$('closeDrawer'),orderLines:$('orderLines'),drawerEmpty:$('drawerEmpty'),drawerPacks:$('drawerPacks'),drawerVials:$('drawerVials'),drawerSubtotal:$('drawerSubtotal'),drawerShipping:$('drawerShipping'),drawerTotal:$('drawerTotal'),researchConfirm:$('researchConfirm'),copyOrder:$('copyOrder'),whatsappOrder:$('whatsappOrder'),toast:$('toast'),connectionError:$('connectionError')};
const F=['company','fullName','vat','address','zip','country','email','phone'],S={products:[],settings:{},cat:'All',q:'',cart:{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>`${S.settings.currencySymbol||'€'}${Number(v||0).toFixed(2)}`;
async function allowed(){const {data,error}=await client.rpc('pure20_can_access_wholesale');if(error)throw error;return data===true}
async function load(){
 if(!await allowed())throw new Error('This account is not approved for wholesale access.');
 const [p,w,s]=await Promise.all([client.from('pure20_products').select('*').eq('active',true).order('sort_order',{ascending:true}),client.from('pure20_wholesale_prices').select('*').eq('active',true),client.from('pure20_settings').select('data').eq('id','wholesale').single()]);
 [p,w,s].forEach(r=>{if(r.error)throw r.error});S.settings=s.data?.data||{};const m=new Map((w.data||[]).map(x=>[x.product_id,x]));
 S.products=(p.data||[]).map((x,i)=>{const q=m.get(x.id);return q?{id:x.id,order:+x.sort_order||i+1,category:x.category||'Other',product:x.product_name||'',variant:x.variant||'',code:x.code||'',stock:+x.stock||0,pack:+q.pack_size||10,price:+q.price_eur||0}:null}).filter(Boolean);
}
const products=()=>S.products, packs=p=>Math.max(0,Math.floor(p.stock/p.pack));
function filtered(){return products().filter(p=>(S.cat==='All'||p.category===S.cat)&&(!S.q||`${p.product} ${p.variant} ${p.code} ${p.category}`.toLowerCase().includes(S.q)))}
function brand(){E.eyebrow.textContent=S.settings.eyebrow||'WHOLESALE / PRIVATE ACCESS';E.pageTitle.textContent=S.settings.title||'Wholesale order builder';E.pageSubtitle.textContent=S.settings.subtitle||'';E.shippingText.textContent=S.settings.shippingText||'Shipping confirmed separately';E.footerNotice.textContent=S.settings.footerNotice||''}
function cats(){const a=['All',...new Set(products().map(p=>p.category))];E.categoryPills.innerHTML=a.map(x=>`<button class="pill ${x===S.cat?'active':''}" data-cat="${esc(x)}">${esc(x)}</button>`).join('')}
function catalogue(){const rows=filtered(),g=new Map();rows.forEach(p=>{if(!g.has(p.category))g.set(p.category,[]);g.get(p.category).push(p)});E.catalogue.innerHTML=[...g].map(([c,a])=>`<section class="category-block"><div class="category-heading"><h2>${esc(c)}</h2><span>${a.length} options</span></div>${a.map((p,i)=>{let q=+S.cart[p.id]||0,n=packs(p);return `<article class="product-card ${n<1?'out':''}"><div class="product-row variant-row" data-id="${p.id}"><div class="product-main"><div class="product-index">${String(i+1).padStart(2,'0')}</div><div><div class="product-name-line"><span class="product-name">${esc(p.product)}</span><span class="product-variant">${esc(p.variant)}</span></div><div class="product-code">${esc(p.code)}</div><div class="pack-note">${p.pack} vials / box · ${n<1?'out of stock':`${n} boxes available`}</div></div></div><div class="product-price"><strong>${money(p.price)}</strong><span>per ${p.pack} vials</span></div><div class="qty-control"><button data-action="minus" ${q<1?'disabled':''}>−</button><input type="number" min="0" max="${n}" value="${q}" ${n<1?'disabled':''}><button data-action="plus" ${q>=n?'disabled':''}>+</button></div></div></article>`}).join('')}</section>`).join('');E.emptyState.hidden=rows.length>0;E.productCount.textContent=new Set(products().map(p=>p.product)).size;E.variantCount.textContent=products().length}
function rows(){return products().filter(p=>(+S.cart[p.id]||0)>0)}
function totals(){const r=rows(),boxes=r.reduce((a,p)=>a+(+S.cart[p.id]||0),0),vials=r.reduce((a,p)=>a+(+S.cart[p.id]||0)*p.pack,0),sub=r.reduce((a,p)=>a+(+S.cart[p.id]||0)*p.price,0),ship=boxes?+S.settings.shippingFlat||0:0;return{r,boxes,vials,sub,ship,total:sub+ship}}
function cart(){const t=totals();E.cartPacks.textContent=t.boxes;E.cartVials.textContent=t.vials;E.headerCartCount.textContent=t.boxes;E.cartSubtotal.textContent=money(t.sub);E.drawerPacks.textContent=t.boxes;E.drawerVials.textContent=t.vials;E.drawerSubtotal.textContent=money(t.sub);E.drawerShipping.textContent=t.boxes?(t.ship?money(t.ship):(S.settings.shippingText||'Confirmed separately')):(S.settings.shippingText||'Confirmed separately');E.drawerTotal.textContent=money(t.total);E.drawerEmpty.hidden=t.r.length>0;E.orderLines.innerHTML=t.r.map(p=>{let q=+S.cart[p.id];return `<div class="order-line" data-id="${p.id}"><div><div class="order-line-name">${esc(p.product)} / ${esc(p.variant)}</div><div class="order-line-meta">${q} × box of ${p.pack} vials · ${q*p.pack} vials total</div></div><div class="order-line-right"><div class="order-line-total">${money(q*p.price)}</div><div class="order-line-actions"><button class="mini-btn" data-da="minus">−</button><button class="mini-btn" data-da="plus" ${q>=packs(p)?'disabled':''}>+</button></div></div></div>`}).join('')}
function qty(id,q){const p=products().find(x=>x.id===id);if(!p)return;q=Math.max(0,Math.min(Math.floor(+q||0),packs(p)));q?S.cart[id]=q:delete S.cart[id];catalogue();cart()}
function toast(x){E.toast.textContent=x;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1800)}
function openD(){E.backdrop.hidden=false;requestAnimationFrame(()=>E.backdrop.classList.add('visible'));E.drawer.classList.add('open');document.body.style.overflow='hidden'}function closeD(){E.drawer.classList.remove('open');E.backdrop.classList.remove('visible');document.body.style.overflow='';setTimeout(()=>E.backdrop.hidden=true,220)}
function save(){localStorage.setItem('pure20_wholesale_customer',JSON.stringify(Object.fromEntries(F.map(id=>[id,$(id).value]))))}function restore(){try{const d=JSON.parse(localStorage.getItem('pure20_wholesale_customer')||'{}');F.forEach(id=>{if(d[id])$(id).value=d[id]})}catch{}}
function txt(){const t=totals(),d=Object.fromEntries(F.map(id=>[id,$(id).value.trim()]));return [`${S.settings.brandName||'PURE20.'} WHOLESALE ORDER REQUEST`,'',...t.r.map(p=>{let q=+S.cart[p.id];return `${q} × ${p.product} ${p.variant} — ${p.pack} vials/box — ${q*p.pack} vials — ${money(q*p.price)}`}),'',`Boxes: ${t.boxes}`,`Total vials: ${t.vials}`,`Subtotal: ${money(t.sub)}`,`Shipping: ${t.ship?money(t.ship):(S.settings.shippingText||'Confirmed separately')}`,`Total: ${money(t.total)}`,'','BUSINESS DETAILS',`Company: ${d.company||'-'}`,`Contact: ${d.fullName||'-'}`,`VAT: ${d.vat||'-'}`,`Address: ${d.address||'-'}`,`Postal code: ${d.zip||'-'}`,`Country: ${d.country||'-'}`,`Email: ${d.email||'-'}`,`Phone: ${d.phone||'-'}`].join('\n')}
function can(){if(!totals().r.length){toast('Add at least one box first.');return false}if(!E.researchConfirm.checked){toast('Confirm the notice first.');return false}save();return true}
async function enter(session){if(!session?.user){E.loginGate.style.display='grid';return}E.accountEmail.textContent=session.user.email||'';try{await load();brand();cats();catalogue();cart();restore();E.loginGate.style.display='none';E.connectionError.hidden=true}catch(e){E.loginError.textContent=e.message;E.loginGate.style.display='grid'}}
E.signInBtn.onclick=async()=>{E.loginError.textContent='';try{const {data,error}=await client.auth.signInWithPassword({email:E.loginEmail.value.trim(),password:E.loginPassword.value});if(error)throw error;await enter(data.session)}catch(e){E.loginError.textContent=e.message}};
E.signUpBtn.onclick=async()=>{E.loginError.textContent='';try{if(E.loginPassword.value.length<8)throw new Error('Use a password of at least 8 characters.');const {data,error}=await client.auth.signUp({email:E.loginEmail.value.trim(),password:E.loginPassword.value});if(error)throw error;E.loginError.style.color='#b8d7c5';E.loginError.textContent='Account created. Confirm your email if required. Access becomes available after approval.';if(data.session)await enter(data.session)}catch(e){E.loginError.style.color='#ef9696';E.loginError.textContent=e.message}};
E.signOutBtn.onclick=async()=>{await client.auth.signOut();location.reload()};
E.search.oninput=e=>{S.q=e.target.value.trim().toLowerCase();catalogue()};E.clearSearch.onclick=()=>{S.q='';E.search.value='';catalogue()};
E.categoryPills.onclick=e=>{const b=e.target.closest('[data-cat]');if(b){S.cat=b.dataset.cat;cats();catalogue()}};
E.catalogue.onclick=e=>{const r=e.target.closest('.variant-row'),b=e.target.closest('[data-action]');if(r&&b)qty(r.dataset.id,(+S.cart[r.dataset.id]||0)+(b.dataset.action==='plus'?1:-1))};
E.catalogue.onchange=e=>{const r=e.target.closest('.variant-row');if(r&&e.target.matches('input'))qty(r.dataset.id,e.target.value)};
E.orderLines.onclick=e=>{const r=e.target.closest('.order-line'),b=e.target.closest('[data-da]');if(r&&b)qty(r.dataset.id,(+S.cart[r.dataset.id]||0)+(b.dataset.da==='plus'?1:-1))};
E.clearCart.onclick=()=>{S.cart={};catalogue();cart()};[E.reviewOrder,E.headerCart].forEach(x=>x.onclick=openD);[E.closeDrawer,E.backdrop].forEach(x=>x.onclick=closeD);F.forEach(id=>$(id).onchange=save);
E.copyOrder.onclick=async()=>{if(!can())return;await navigator.clipboard.writeText(txt());toast('Wholesale order copied.')};E.whatsappOrder.onclick=()=>{if(!can())return;const n=String(S.settings.whatsappNumber||'').replace(/\D/g,'');window.open(n?`https://wa.me/${n}?text=${encodeURIComponent(txt())}`:`https://wa.me/?text=${encodeURIComponent(txt())}`,'_blank','noopener')};
const {data:{session}}=await client.auth.getSession();await enter(session);
})();