(async()=>{
const C=window.PURE20_SUPABASE_CONFIG||{},client=window.supabase.createClient(C.url,C.key,{auth:{persistSession:true,autoRefreshToken:true}}),$=id=>document.getElementById(id);
const E={gate:$('loginGate'),email:$('emailInput'),pass:$('passwordInput'),login:$('loginButton'),err:$('loginError'),out:$('signOut'),body:$('priceBody'),ae:$('accessEmail'),al:$('accessLabel'),add:$('addAccess'),list:$('accessList'),title:$('setTitle'),sub:$('setSubtitle'),ship:$('setShipping'),wa:$('setWhatsapp'),st:$('setShippingText'),foot:$('setFooter'),save:$('saveSettings')};let P=[],W=[],A=[],S={};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function admin(){const {data,error}=await client.rpc('is_pure20_admin');if(error)throw error;if(data!==true)throw new Error('This account is not a PURE20 administrator.')}
async function load(){await admin();const [p,w,a,s]=await Promise.all([client.from('pure20_products').select('*').order('sort_order',{ascending:true}),client.from('pure20_wholesale_prices').select('*'),client.from('pure20_wholesale_access').select('*').order('email'),client.from('pure20_settings').select('data').eq('id','wholesale').single()]);[p,w,a,s].forEach(r=>{if(r.error)throw r.error});P=p.data||[];W=w.data||[];A=a.data||[];S=s.data?.data||{};render()}
function render(){const m=new Map(W.map(x=>[x.product_id,x]));E.body.innerHTML=P.map(p=>{const w=m.get(p.id)||{pack_size:10,price_eur:0,active:false};return `<tr data-id="${p.id}"><td><strong>${esc(p.product_name)}</strong><div class="admin-note">${esc(p.code||'')}</div></td><td>${esc(p.variant||'')}</td><td>${+p.stock||0}</td><td><input class="pack" data-f="pack" type="number" min="1" value="${+w.pack_size||10}"></td><td><input class="price" data-f="price" type="number" min="0" step="0.01" value="${(+w.price_eur||0).toFixed(2)}"></td><td><select data-f="active"><option value="true" ${w.active?'selected':''}>Active</option><option value="false" ${!w.active?'selected':''}>Hidden</option></select></td><td><button class="btn alt" data-save>Save</button></td></tr>`}).join('');E.list.innerHTML=A.length?A.map(a=>`<div class="accessitem" data-email="${esc(a.email)}"><div><strong>${esc(a.email)}</strong><div class="admin-note">${esc(a.label||'')}</div></div><span>${a.active?'Active':'Disabled'}</span><div><button class="btn alt" data-toggle>${a.active?'Disable':'Enable'}</button> <button class="btn danger" data-del>Delete</button></div></div>`).join(''):'<p class="admin-note">No approved customer emails yet.</p>';E.title.value=S.title||'Wholesale order builder';E.sub.value=S.subtitle||'';E.ship.value=+S.shippingFlat||0;E.wa.value=S.whatsappNumber||'';E.st.value=S.shippingText||'Shipping confirmed separately';E.foot.value=S.footerNotice||''}
E.login.onclick=async()=>{E.err.textContent='';try{const {data,error}=await client.auth.signInWithPassword({email:E.email.value.trim(),password:E.pass.value});if(error)throw error;await admin();E.gate.style.display='none';await load()}catch(e){E.err.textContent=e.message}};
E.out.onclick=async()=>{await client.auth.signOut();location.reload()};
E.body.onclick=async e=>{const b=e.target.closest('[data-save]');if(!b)return;const r=b.closest('tr');try{const {error}=await client.from('pure20_wholesale_prices').upsert({product_id:r.dataset.id,pack_size:+r.querySelector('[data-f="pack"]').value||10,price_eur:+r.querySelector('[data-f="price"]').value||0,active:r.querySelector('[data-f="active"]').value==='true'});if(error)throw error;await load()}catch(x){alert(x.message)}};
E.add.onclick=async()=>{try{const email=E.ae.value.trim().toLowerCase();if(!email.includes('@'))throw new Error('Enter a valid email.');const {error}=await client.from('pure20_wholesale_access').upsert({email,label:E.al.value.trim(),active:true});if(error)throw error;E.ae.value='';E.al.value='';await load()}catch(x){alert(x.message)}};
E.list.onclick=async e=>{const row=e.target.closest('[data-email]');if(!row)return;try{if(e.target.closest('[data-del]')){const {error}=await client.from('pure20_wholesale_access').delete().eq('email',row.dataset.email);if(error)throw error}if(e.target.closest('[data-toggle]')){const a=A.find(x=>x.email===row.dataset.email),{error}=await client.from('pure20_wholesale_access').update({active:!a.active}).eq('email',row.dataset.email);if(error)throw error}await load()}catch(x){alert(x.message)}};
E.save.onclick=async()=>{try{S={...S,title:E.title.value.trim(),subtitle:E.sub.value.trim(),shippingFlat:+E.ship.value||0,whatsappNumber:E.wa.value.trim(),shippingText:E.st.value.trim(),footerNotice:E.foot.value.trim()};const {error}=await client.from('pure20_settings').upsert({id:'wholesale',data:S});if(error)throw error;E.save.textContent='Saved';setTimeout(()=>E.save.textContent='Save settings',1200)}catch(x){alert(x.message)}};
const {data:{session}}=await client.auth.getSession();if(session){try{await admin();E.gate.style.display='none';await load()}catch(e){await client.auth.signOut();E.err.textContent=e.message}}
})();